services:
    api:
        build:
            context: ./backend/src/python
            dockerfile: Dockerfile
        container_name: health-app-api
        # ports:
        #     - "8080:8080"
        networks:
            - backend
        environment:
            - INFLUX_HOST=${INFLUX_HOST}
            - INFLUX_TOKEN=${INFLUX_TOKEN}
            - INFLUX_ORG=${INFLUX_ORG}
            - INFLUX_DATABASE=${INFLUX_DATABASE}

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: health-app-frontend
        ports:
            - "13000:80"
        networks:
            - backend
        depends_on:
            - api

networks:
    backend:
        external: true
