services:
    api:
        build:
            context: ./backend/src/go
            dockerfile: Dockerfile.dev
        container_name: health-app-api
        ports:
            - "13001:13001"
        networks:
            - backend
        environment:
            - INFLUX_HOST=${INFLUX_HOST}
            - INFLUX_TOKEN=${INFLUX_TOKEN}
            - INFLUX_ORG=${INFLUX_ORG}
            - INFLUX_DATABASE=${INFLUX_DATABASE}

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: health-app-frontend
        ports:
            - "13000:80"
        networks:
            - backend
            - proxy
        depends_on:
            - api
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend-router.rule=Host(`health.myerslab.me`)"
            - "traefik.http.routers.frontend-router.entrypoints=websecure"
            - "traefik.http.routers.frontend-router.tls=true"
            - "traefik.http.routers.frontend-router.tls.certresolver=cloudflare"
            - "traefik.http.services.frontend-service.loadbalancer.server.port=80"
            - "traefik.docker.network=proxy"

networks:
    backend:
        external: true
    proxy:
        external: true
